version: "3.8"
services:
  face-app-api:
    container_name: backend
    build: ./
    command: npm start
    environment:
      POSTGRES_URI: postgresql://postgres:Micheal823@postgres:5432/face-app-docker
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "2000:2000"
    volumes:
      - ./:/face-app-api
  
  # Postgres
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Micheal823
      POSTGRES_HOST: postgres
      POSTGRES_DB: face-app-docker
    build: ./postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"